version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  node:
    build:
      context: ./backend-node
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./backend-node:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/sleep_ai
      - PYTHON_PREDICT_URL=http://python:5000/predict
      - JWT_SECRET=ReplaceWithAStrongSecret
    depends_on:
      - mongo
      - python

  python:
    build:
      context: ./microservice-predict
      dockerfile: Dockerfile
    command: python predict_service.py
    volumes:
      - ./microservice-predict:/app
    ports:
      - "5000:5000"

volumes:
  mongo_data:
